'use client'

import { motion } from 'framer-motion'
import { Quote } from 'lucide-react'
import Image from 'next/image'

const testimonials = [
  {
    quote: "This platform has completely transformed how we think about employer branding. It is no longer a chore, it is a competitive advantage.",
    author: "Sarah Chen",
    role: "VP of People, Notion",
    image: "https://i.pravatar.cc/150?u=sarah"
  },
  {
    quote: "The authentic content generated by our employees has seen 4x higher engagement than our best performing paid ads.",
    author: "Marcus Rodriguez",
    role: "Director of Talent, Airbnb",
    image: "https://i.pravatar.cc/150?u=marcus"
  }
]

export default function Testimonials() {
  return (
    <section className="w-full py-32 px-6 bg-white overflow-hidden">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          {testimonials.map((t, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: i % 2 === 0 ? -20 : 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: i * 0.1 }}
              viewport={{ once: true }}
              className="relative p-12 rounded-[3rem] bg-gray-50 flex flex-col gap-8"
            >
              <Quote className="w-12 h-12 text-blue-600/20 absolute top-10 right-10" />
              <p className="text-2xl md:text-3xl font-medium text-black leading-tight tracking-tight italic">
                "{t.quote}"
              </p>
              <div className="flex items-center gap-4 mt-auto">
                <div className="w-12 h-12 rounded-full overflow-hidden bg-gray-200 relative">
                  <Image src={t.image} alt={t.author} fill className="object-cover" unoptimized />
                </div>
                <div>
                  <h4 className="font-semibold text-black">{t.author}</h4>
                  <p className="text-sm text-gray-500">{t.role}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
